### ISSUE TITLE
missing network manual configuration

### ISSUE THREAD

**Issue by isghe** [IBM-Blockchain-Archive/marbles#1]
Hi, 

> Setup Options:
> So the cc is great and all but first we need a blockchain network. Choose 1 option below:
> 
> (1) Deploy the app on my local machine and create a network **manually**
> 
> OR
> 
> (2) Deploy the app and network at once on Bluemix. Simply click this button     Deploy to Bluemix then continue hereptions:
> So the cc is great and all but first we need a blockchain network. Choose 1 option below:
> 
> (1) Deploy the app on my local machine and create a network **manually**
> 
> OR
> 
> (2) Deploy the app and network at once on Bluemix. Simply click this button     Deploy to Bluemix then continue here

manually link is broken: "https://github.com/IBM-Blockchain/marbles/blob/master/tutorial_part1.md#Network"
and so so network manual configuration is missing.

thanks.

**Comment by dshuffma-ibm** [comment]
Thanks for identifying the bad link. All fixed in commit [a075f580f0f7a37f896a276bd4c27a30fca1ce78](https://github.com/IBM-Blockchain/marbles/commit/a075f580f0f7a37f896a276bd4c27a30fca1ce78)

**Comment by isghe** [comment]
Thanks for reply, but I have a doubt now: is it necessary to login into [Bluemix](https://console.ng.bluemix.net) to setup a network manually? How can I deploy the app on my local machine and setup a network, without the need of a login on [Bluemix](https://console.ng.bluemix.net)?

thanks.

**Comment by mastersingh24** [comment]
If you want to use a Blockchain network which is running in the cloud (and not locally), then you will need a Bluemix account and you'll need to login to Bluemix.

It is technically possible to run the marbles app against a blockchain network running on your local machine as well, but that is not covered in this tutorial.

In order to run a network on your local machine, you will want to check out https://github.com/openblockchain/obc-docs and https://github.com/openblockchain/obc-peer.  The easiest thing to do is to start with the Vagrant developer image - https://github.com/openblockchain/obc-docs/blob/master/dev-setup/devenv.md.

Once you have your network running on your local machine, you can modify the app to use your local network credentials.  You'll need to modify [app.js](https://github.com/IBM-Blockchain/marbles/blob/master/app.js) starting at around line 135:

```
var manual ={
  "credentials": {
    "peers": [
      {
        "discovery_host": "169.44.63.197",
        "discovery_port": "33953",
        "api_host": "169.44.63.197",
        "api_port": "33954",
        "type": "peer",
        "network_id": "3fc3b557-312b-4bbe-bae7-cb08228e5935",
        "id": "3fc3b557-312b-4bbe-bae7-cb08228e5935_vp1",
        "api_url": "http://169.44.63.197:33954"
```

You'll need to replace the host(s) and ports with information about your local network.

Hope this helps.  The obc-peer project will eventually be producing Docker images you can use as well.  There is not a lot of documentation on it today, but withing the [obc-peer](https://github.com/openblockchain/obc-peer) project you'll also find Docker / Docker Compose files as well.  So an alternative is to Vagrant is to install Docker and Docker Compose locally and spin up a network using Docker Compose as well.

Hope this helps.

Out of curiosity, is there a reason you don't want to use Bluemix to run your network?

**Comment by GauriSawant** [comment]
Hi,

We are trying to use Bluemix network for our blockchain application. but, we are not able to figure out the accessibility for using it for a multi peer application.Can you help us resolve this on an urgent basis.

**Comment by dshuffma-ibm** [comment]
I don't quite understand.  Could you open up your own issue and provide more details/rephrase?  

As a stab in the dark, you may want to look at how ibc.load() is built (in SDK code) and build your own version that registers enroll IDs in a manner that works for your setup.  Line 56 in index.js  https://github.com/IBM-Blockchain/ibm-blockchain-js/blob/master/index.js

**Comment by GauriSawant** [comment]
Hi I have created my blockchain network having 2 Vps and 1 CA using obc-peer, I would want to know how shall i take CA's server details in order to replace them in the app.js? Is there any tutorial to explain how to deploy a node.js application is deployed on local blockchain network? Please reply urgent!! need this for a POC :)

**Comment by dshuffma-ibm** [comment]
**First I would like to request that people please make their own issues for unique problems.**

Second feeding network data to marbles is done via the SDK.  Look over at its readme for its input near the `ibc.load()` [documentation](https://github.com/IBM-Blockchain/ibm-blockchain-js).  You will be feeding it data that looks like:

```
"api_host": "xxx.xxx.xxx.xxx",
"api_port": "xxxxx",
"api_port_tls": "xxx",
"id": "xxxxxx-xxxx-xxx-xxx-xxxxxxxxxxxx_vpx"
```

When in doubt just mimic the marbles setup in its `app.js`.
