### ISSUE TITLE
Delete functionality

### ISSUE THREAD

**Issue by pawanjay176** [IBM-Blockchain-Archive/marbles#11]
The blockchain being an append only ledger, doesn't the delete functionality go against the principles of a blockchain?

**Comment by dshuffma-ibm** [comment]
Think of the ledger as tracking actions rather than absolute state.  Creating a marble is an action so it gets appended to the ledger. Trading it is another action, gets appended.  Deleting is just another action and it gets appended to the ledger. 

Now the chaincode's state space is a separate entity.  From the chaincode's point of view it was removed from the state.

TLDR: The delete function does not remove the record of the original marble from the ledger. Its still in the ledger, its just no longer in the chaincode's state space.

**Comment by pawanjay176** [comment]
Thanks! Clear now. Could you please point me to the code where writing actions to the ledger is implemented?

**Comment by dshuffma-ibm** [comment]
That would be in the chaincode repo (separate than the app's repo) over here:
https://github.com/IBM-Blockchain/marbles-chaincode/blob/master/hyperledger/part1/part1_chaincode.go

Look at the function at line 219. Particularly the `stub.PutState()` part at line 268.

As a preface to marbles you may want to walk through [learn chaincode](https://github.com/IBM-Blockchain/learn-chaincode)
