### ISSUE TITLE
Viewing transaction history

### ISSUE THREAD

**Issue by pawanjay176** [IBM-Blockchain-Archive/marbles#12]
How can I view the entire life cycle of the marble since its inception?
For e.g. when created, Bob was the owner, then it was traded for 2 white marbles at block number 12 with Leroy

**Comment by dshuffma-ibm** [comment]
There is currently no _easy_ way to figure this out.  Without modifying any chaincode you could query on every block to get transaction details, decode it, and rebuild the state yourself.  This would be a nightmare by most standards. 

Alternatively you could modify the chaincode to keep a historic array of ownership.  This would be really easy and accomplish what you want, but it does feel a little silly/redundant. (since half of the point of blockchain is to have immutable history) This is my quick fix suggestion.

A real fix would be to gain this feature in Hyperledger (the blockchain code base).  I would advise you to open an issue on the [Hyperledger Fabric](https://github.com/hyperledger/fabric/issues) to gain the feature to query chaincode state at a particular block height.  This is not yet possible, but is technically feasible.

**Comment by bparasuram** [comment]
Is there any update to this problem / issue?

**Comment by dshuffma-ibm** [comment]
@bparasuram Yeah, so in v4.0/v3.0 marbles you can see the transaction history of each marble by right clicking a marble or by left clicking the audit button then the left clicking a marble.

this is using the chaincode shim function [GetHistoryForKey()](https://github.com/IBM-Blockchain/marbles/blob/af00595642673dc4befb800c42a5731d8c1774ac/chaincode/src/marbles/read_ledger.go#L176)
