### ISSUE TITLE
No users

### ISSUE THREAD

**Issue by cyberSlav** [IBM-Blockchain-Archive/marbles#123]
it connects, but there are no users with whom i can trade the marbles.

**Comment by dshuffma-ibm** [comment]
next time this happens check your node.js console/terminal logs.  its pretty talkative. you should see errors of some sort.

since those are long gone, click the setup button, then go to the `Register Marble Owners` section.  click the `Register` button to make new users.  if something is wrong, you may see errors again in the console.

![image](https://user-images.githubusercontent.com/16085295/27969960-ffcae87c-631a-11e7-8bb9-8c3c844118ee.png)
