### ISSUE TITLE
Install_chaincode.js installing chaincode from which directory. Where is the chaincode exactly.

### ISSUE THREAD

**Issue by manasabingi** [IBM-Blockchain-Archive/marbles#202]
I just removed all go files from the marbles directory , then i had run the install_chaincode.js script. my chain code was installed successfully. 
Shall i know from where it is getting chain code.
i just tried to add new attribute, but i was getting an error "incorrect number of arguments . Expecting 3" but i don't have any file contains that (i.e., incorrect number of arguments . Expecting 3) string. that's why i checked if any edit's of go files are effecting on the chain code installation or not. 
Final result is without having at least one go file in marbles directory i am able to install and instantiate chain code and ui also.
Any one just give me some knowledge "From where install_chaincode.js script getting marbles chain code & if i require any edit's in chain code where i have to edit."
thanks in advance.

**Comment by dshuffma-ibm** [comment]
chaincode is typically installed from `<marbles root>/chaincode/src/marbles`. but this is changeable with the `path_2_chaincode` parameter in the install script. 

i tried to see what happens if you remove *all* the chaincode. and well... it does install successfully!  this is quite strange, but it would appear that Fabric/sdk allows you to install absolutely nothing. But you will be unable to instantiate it, b/c there are no build-able files.

make sure you are changing your chaincode ID every time. instantiate must be called on a chaincode ID that does not currently exists (you could use `Upgrade`, but lets stick to this flow). after you installed/instantiated a new version **make sure your connection profile is pointing to the new chaincode id/version!**

i have a feeling you are sending your invokes/queries to the previous chaincode and that's why you keep seeing that message.

**Comment by dshuffma-ibm** [comment]
closing, inactivity
