### ISSUE TITLE
Chaincode loading from repo

### ISSUE THREAD

**Issue by pawanjay176** [IBM-Blockchain-Archive/marbles#22]
Any particular reason that the server loads the chaincode from another repo? 
Wouldn't it be easier if you can have the chaincode file in the same directory as your app.js and loading from there?
Saves the hassle of pushing every small change to your chaincode.

**Comment by dshuffma-ibm** [comment]
Two poor reasons:
1. At one point I was concerned that the hash the gets generated to form your chaincode ID would include everything in the github repo that we tell it to deploy from. This turned out not to be the case... 
2. The REST based SDK downloads the entire repo as a zip. This could become time consuming if your application is large. ie slow down iterative development.

```
Saves the hassle of pushing every small change to your chaincode.
```

well hold on, you still need to push every chaincode change to github. The REST interface to Hyperledger requires us to send a github go GET url. We cannot send chaincode from a local folder. Stay tuned for the new SDK, which uses gRPC and it can do that.
