### ISSUE TITLE
Running on debian system

### ISSUE THREAD

**Issue by epyzerknapp** [IBM-Blockchain-Archive/marbles#29]
If you want to run locally on the Debian-type OS's, you must also install the package nodejs-legacy in order to sucessfully perform npm install.  It would be great if you added this to the installation/setup notes :)

**Comment by dshuffma-ibm** [comment]
so the heart of the issue is the package named `node` is taken in those systems, thus you have to install `nodejs`.  so when everyone else is sending the command `node app.js` you would need to type `nodejs app.js`.  but then any script that uses the command `node` will fail. Therefore you should create a sym link to convert `node` -> `nodejs` which his what `nodejs-legacy` does.

I kind of view this as a prereq issue and not something in the scope of marbles. We don't list Node.js installation instructions for any OS's. But now that we have an issue on it, maybe it will be easier for the next guy.

[Node.js Package Installation](https://nodejs.org/en/download/package-manager/)
