### ISSUE TITLE
[ERROR] Tag latest not found in repository docker.io/ibmblockchain/fabric-membersrvc

### ISSUE THREAD

**Issue by enbochen** [IBM-Blockchain-Archive/marbles#64]
Using Docker Compose Local to run Hyperledger Network 
follow the documentation: [https://hub.docker.com/r/ibmblockchain/fabric-peer/](https://hub.docker.com/r/ibmblockchain/fabric-peer/)
Step 5. Try to run one of the two docker compose files, single-peer-ca.yaml or four-peer-ca.yaml.
Get Error like this:

`$ sudo docker-compose -f four-peer-ca.yaml up`
`WARNING: The ARCH_TAG variable is not set. Defaulting to a blank string.`
`Pulling membersrvc (ibmblockchain/fabric-membersrvc:latest)...`
`Pulling repository docker.io/ibmblockchain/fabric-membersrvc`
`ERROR: Tag latest not found in repository docker.io/ibmblockchain/fabric-membersrvc`

Docker Version:
docker-compose version 1.5.2, build unknown
docker-py version: 1.8.0
CPython version: 2.7.12
OpenSSL version: OpenSSL 1.0.2g  1 Mar 2016

System Version:
Distributor ID:	Ubuntu
Description:	Ubuntu 16.04 LTS
Release:	16.04
Codename:	xenial

**Comment by dshuffma-ibm** [comment]
are you using marbles v3.0 and the connect-a-thon hyperledger network? also were you one of the invited participants? you will need to know a user/password to work with the connect-a-thon flow.

at any rate you may get better help by posting in the [connect-a-thon](https://github.com/IBM-Blockchain/connectathon) repo instead of marbles.
